### ISSUE TITLE
Use with OpenTelemetry collector

### ISSUE THREAD

**Issue by tsloughter** [newrelic/opentelemetry-exporter-go#11]
Is this meant to be usable as an exporter in the Otel Collection, https://github.com/open-telemetry/opentelemetry-collector? Like the exporters found in the contrib repo https://github.com/open-telemetry/opentelemetry-collector-contrib/

**Comment by MrAlias** [comment]
@tsloughter this is meant to be an exporter for the [OTel Go](https://github.com/open-telemetry/opentelemetry-go) project. I'm working on an exporter for the collector currently: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/229

**Comment by tsloughter** [comment]
Ah ok, great :+1:
