### ISSUE TITLE
Remove or overwrite the service name

### ISSUE THREAD

**Issue by MrAlias** [newrelic/opentelemetry-exporter-go#21]
Currently the exporter requires a service name to be provided on creation. However, this exporter may export for multiple 'services'.  The common pattern in OpenTelemetry is to use an appropriate attribute of a resource (linked to a trace or metric provider) to identify the service producing the telemetry.

The exporter should at a minimum use the `Resource` value to overwrite the existing `Exporter` service name, but it might also be worth thinking about just expecting the service name to be provided by a resource by default. It is more appropriate to have the Resource define this it would seem (something the user creates) than the exporter (something use user uses).

**Comment by cxhansen** [comment]
I think I agree. So I believe the order of precedence for the service.name should be:

1. attribute already on telemetry
2. defined by the resource
3. configured by the exporter

But will the "user" really create the resource in most cases? Ideally, the resource is discovered through instrumentation (and then potentially overridden by resource configuration, e.g. an environment variable passed in).
