### ISSUE TITLE
Update documentation to help new users with how to use this exporter

### ISSUE THREAD

**Issue by jodeev** [newrelic/opentelemetry-exporter-go#32]
Documentation should cover how customer should use the exporter and where to go to learn how to instrument their code.

There is boilerplate content available from the docs team, and can be found on slack #docs-opentelemetry or contact @rhetoric101 

**Acceptance Criteria:**
* Docs available in the exporter repo AND at docs.newrelic.com
* Docs in repo (can point to docs.newrelic.com as needed) guide user as to 
** where to start to instrument your Go service using OpenTelemetry,
** how to use the exporter with a collector or with NR infinite tracing, 
* NR docs site is updated to:
** points to GitHub docs as needed
* A user should be able to:
** Start from our exporter docs and be able to navigate to everything that they need to send trace data (using examples) that includes all basic span types - http, dB, externals - within 15 minutes

**Comment by schmurfy** [comment]
Since it looks like a good place to ask:
- I managed to find where to create my insert key (seriously what is this insight thing and why is it split from the standard newrelic website...)
- I managed to send my first event using curl and json

And now I instrumented a real app using this exporter but my traces are nowhere to find found in APM or entity explorer, I have no idea if the export are successful or not.

**Comment by andrewhiles** [comment]
@schmurfy were you able to make any progress with this? I am experiencing something similar currently. I've added the instrumentation in my Golang application for telemetry to be sent to NewRelic but unable to view traces anywhere on NR's website. Similar to yourself, I struggled to identify the correct API key to use as well as it was located on a different webpage from the standard API keys.

**Comment by schmurfy** [comment]
I managed to get something to show up once but I eventually just gave up on newrelic.

**Comment by jodeev** [comment]
Sorry we've been slow with our response here. We are working on improving our documentation.

We will track EU configuration as part of this work https://github.com/newrelic/opentelemetry-exporter-go/issues/61 .
