### ISSUE TITLE
new version v0.14.0 of opentelemetry-go broke the exporter

### ISSUE THREAD

**Issue by weizhang9** [newrelic/opentelemetry-exporter-go#41]
Hi,

Opentelemetry-go has released a new version recently https://github.com/open-telemetry/opentelemetry-go/releases/tag/v0.14.0 where they moved the package paths like `otel/api/global` and `otel/api/metric` which has unfortunately broken the current tag v0.13.0 of this package. Would there be any update in the near future to fix this please? Thanks!

**Comment by MrAlias** [comment]
@weizhang9 thanks for using the exporter! We have an open PR to address this upgrade here: https://github.com/newrelic/opentelemetry-exporter-go/pull/40

It is waiting to be reviewed and should be merged and released within the next week or two. Please be sure to take a look at that PR and leave a review.

@weizhang9 out of curiosity, what version of Go are you using when running the exporter and are you using Go's module system?

**Comment by weizhang9** [comment]
Hi @MrAlias thank you for responding, and glad to hear it'll be addressed soon!😄

We use go module, the go version specified in the module of the project that we use the exporter is 1.12, but my local binary is 1.15.

The exporter is working really well and helps us a lot! Thank you all for your hard work!🙏
