### ISSUE TITLE
New Relic Go OpenTelemetry Documentation

### ISSUE THREAD

**Issue by RichVanderwal** [newrelic/opentelemetry-exporter-go#42]
New Relic documentation for Go OpenTelemetry, including examples to guide users as to how to instrument code (referencing the OTel "Quickstart" guide), and how best to send data for Go services to New Relic (referencing the overview content which will cover exporter vs collector vs ...)

**Comment by jodeev** [comment]
This is going into the exporter README and we are going to have a [single common document ](https://docs.google.com/document/d/1tzCHVmiA6Rnz8D9eDkc7DF5wiFEex7uHSD9d0R4slBE/edit#)on docs.newrelic that points to the individual repos for each language, as applicable.

**Comment by RichVanderwal** [comment]
This Quickstart and the linked sample application need to be re-worked to accommodate the new API changes in Go OpenTelemetry v0.16.0.
