### ISSUE TITLE
How to show tracing information in the APM Distributed Tracing Page

### ISSUE THREAD

**Issue by HenriBeck** [newrelic/opentelemetry-exporter-go#46]
The default integration works great and smoothly and sends the data as expected to NewRelic and it can be queried from the Distributed Tracing App.

However, what was straight forward for us is how we can also make the tracing data available in the `Distributed Tracing` page of our APM application.
In the end, we found a workaround where we can set the `entity.guid` and `entityGuid` as attributes on all the spans manually, this however looks more like a workaround than a proper solution for us.

Is there any better attribute for achieving the behavior or is this the expected way how it should work?

**Comment by RichVanderwal** [comment]
Hi @HenriBeck , thanks for writing in! That _does_ seem like a very manual way to make sure Distributed Tracing is working. 

I'm a little bit confused about what you mean by "Distributed Tracing App" AND "Distributed Tracing page" in your description above. Also, we'd like to know how you're making spans, if they're external calls, and what framework (if any) you're using.

Could you open up a support ticket at https://support.newrelic.com/ ? We'll continue the conversation there and look for a tidier solution for you.

**Comment by HenriBeck** [comment]
@RichVanderwal I'm referring to the following page:

<img width="236" alt="Screenshot 2020-12-30 at 20 39 48" src="https://user-images.githubusercontent.com/8514706/103377331-6a820380-4adf-11eb-9db7-08e52824c07b.png">

The distributed tracing works, but the data only shows up in the Distributed Tracing Nerdlet when querying for the specific application. However, it doesn't normally show up in the Distributed Tracing page integrated in the APM.  
For example, this works when using the distributed tracing from the [newrelic-go-agent](https://github.com/newrelic/go-agent) where it correctly associates the tracing data with the APM application.

**Comment by RichVanderwal** [comment]
I've asked our Distributed Tracing team to see if there's a better way to get these traces to show up in the Distributed Tracing UI.

**Comment by RichVanderwal** [comment]
Hello @HenriBeck , according to our Distributed Tracing team right now you should be able to just set a `service.name` on those spans. We now synthesize an `entity.guid` for you. Please let us know if it's not working for you.

**Comment by HenriBeck** [comment]
Hey @RichVanderwal, I checked this and while an `entity.guid` is being added to each span, it's somehow not the correct one.

The entity guid isn't the one from our APM Service but rather from a newly created entity of the type `integration-reported-services`.
