### ISSUE TITLE
incompatible with  go.opentelemetry.io/otel/sdk v0.20.0 

### ISSUE THREAD

**Issue by nicksherron** [newrelic/opentelemetry-exporter-go#91]
This is extremely frustrating. If new relic is going to advertise opentelemtry support and then add a opentelemetry go exporter library then at least keep the damn thing up to date!

```

  github.com/newrelic/opentelemetry-exporter-go/newrelic imports
        go.opentelemetry.io/otel/sdk/export/trace: module go.opentelemetry.io/otel/sdk@latest found (v0.20.0), but does not contain package go.opentelemetry.io/otel/sdk/export/trace

```

**Comment by alanwest** [comment]
@nicksherron Thanks for bringing this to our attention. Apologies for the extra work this created for you. I agree we've neglected to keep this up to date.

Something to consider is to migrate over to using New Relic's native OTLP endpoint. We'll be deprecating this exporter in the near future in favor of folks simply using the [Go SDK's OTLP exporter](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/otlp).

Our native OTLP endpoint is currently in pre-release and you can [sign up here](https://docs.newrelic.com/whats-new/2021/04/native-support-opentelemetry).

**Comment by nicksherron** [comment]
@alanwest Thank you for your thoughtful and thorough response, and I apologize for the harshness of my original comment. I was just frustrated. Thanks again, cheers!
